-- Seed de 10 perfis fictícios para teste da funcionalidade Tinder de análise de leads
-- Estes dados são fictícios e destinados apenas para demonstração e testes

INSERT INTO public.fichas (
  nome,
  telefone,
  email,
  idade,
  projeto,
  scouter,
  supervisor,
  localizacao,
  latitude,
  longitude,
  local_da_abordagem,
  modelo,
  etapa,
  ficha_confirmada,
  foto,
  cadastro_existe_foto,
  presenca_confirmada,
  valor_ficha,
  aprovado,
  criado
) VALUES
  -- Perfil 1: Ana Silva
  (
    'Ana Silva',
    '(11) 98765-4321',
    'ana.silva@email.com',
    '23',
    'Fashion Week SP',
    'Carlos Mendes',
    'Maria Santos',
    'Shopping Morumbi, São Paulo',
    -23.6226,
    -46.6997,
    'Shopping Morumbi',
    'Modelo Feminino',
    'Contato',
    'Sim',
    'https://randomuser.me/api/portraits/women/1.jpg',
    'SIM',
    'Sim',
    150.00,
    NULL,
    NOW() - INTERVAL '5 days'
  ),
  
  -- Perfil 2: Bruno Costa
  (
    'Bruno Costa',
    '(21) 99876-5432',
    'bruno.costa@email.com',
    '28',
    'Editorial Rio',
    'Fernanda Lima',
    'João Pedro',
    'Copacabana, Rio de Janeiro',
    -22.9688,
    -43.1829,
    'Praia de Copacabana',
    'Modelo Masculino',
    'Agendado',
    'Sim',
    'https://randomuser.me/api/portraits/men/2.jpg',
    'SIM',
    'Sim',
    200.00,
    NULL,
    NOW() - INTERVAL '4 days'
  ),
  
  -- Perfil 3: Carla Rodrigues
  (
    'Carla Rodrigues',
    '(11) 97654-3210',
    'carla.rodrigues@email.com',
    '21',
    'Campanha Verão',
    'Carlos Mendes',
    'Maria Santos',
    'Parque Ibirapuera, São Paulo',
    -23.5875,
    -46.6577,
    'Parque Ibirapuera',
    'Modelo Feminino',
    'Convertido',
    'Sim',
    'https://randomuser.me/api/portraits/women/3.jpg',
    'SIM',
    'Sim',
    180.00,
    NULL,
    NOW() - INTERVAL '3 days'
  ),
  
  -- Perfil 4: Daniel Oliveira
  (
    'Daniel Oliveira',
    '(85) 98765-1234',
    'daniel.oliveira@email.com',
    '25',
    'Desfile Nordeste',
    'Patricia Souza',
    'João Pedro',
    'Praia de Iracema, Fortaleza',
    -3.7172,
    -38.5128,
    'Praia de Iracema',
    'Modelo Masculino',
    'Contato',
    'Aguardando',
    'https://randomuser.me/api/portraits/men/4.jpg',
    'SIM',
    null,
    150.00,
    NULL,
    NOW() - INTERVAL '2 days'
  ),
  
  -- Perfil 5: Eduarda Martins
  (
    'Eduarda Martins',
    '(31) 99123-4567',
    'eduarda.martins@email.com',
    '22',
    'Moda BH',
    'Roberto Alves',
    'Maria Santos',
    'Savassi, Belo Horizonte',
    -19.9389,
    -43.9319,
    'Savassi',
    'Modelo Feminino',
    'Agendado',
    'Sim',
    'https://randomuser.me/api/portraits/women/5.jpg',
    'SIM',
    'Sim',
    170.00,
    NULL,
    NOW() - INTERVAL '1 day'
  ),
  
  -- Perfil 6: Felipe Santos
  (
    'Felipe Santos',
    '(41) 98234-5678',
    'felipe.santos@email.com',
    '27',
    'Campanha Outono',
    'Juliana Torres',
    'João Pedro',
    'Centro, Curitiba',
    -25.4372,
    -49.2699,
    'Centro de Curitiba',
    'Modelo Masculino',
    'Contato',
    'Sim',
    'https://randomuser.me/api/portraits/men/6.jpg',
    'SIM',
    null,
    160.00,
    NULL,
    NOW() - INTERVAL '6 hours'
  ),
  
  -- Perfil 7: Gabriela Pereira
  (
    'Gabriela Pereira',
    '(51) 97345-6789',
    'gabriela.pereira@email.com',
    '24',
    'Fashion Sul',
    'Marcos Silva',
    'Maria Santos',
    'Gasômetro, Porto Alegre',
    -30.0346,
    -51.2177,
    'Usina do Gasômetro',
    'Modelo Feminino',
    'Convertido',
    'Sim',
    'https://randomuser.me/api/portraits/women/7.jpg',
    'SIM',
    'Sim',
    190.00,
    NULL,
    NOW() - INTERVAL '12 hours'
  ),
  
  -- Perfil 8: Henrique Lima
  (
    'Henrique Lima',
    '(71) 98456-7890',
    'henrique.lima@email.com',
    '26',
    'Verão Bahia',
    'Amanda Costa',
    'João Pedro',
    'Pelourinho, Salvador',
    -12.9714,
    -38.5124,
    'Pelourinho',
    'Modelo Masculino',
    'Agendado',
    'Aguardando',
    'https://randomuser.me/api/portraits/men/8.jpg',
    'NÃO',
    'Sim',
    140.00,
    NULL,
    NOW() - INTERVAL '3 hours'
  ),
  
  -- Perfil 9: Isabela Ferreira
  (
    'Isabela Ferreira',
    '(61) 99567-8901',
    'isabela.ferreira@email.com',
    '20',
    'Capital Fashion',
    'Lucas Andrade',
    'Maria Santos',
    'Lago Paranoá, Brasília',
    -15.7942,
    -47.8825,
    'Lago Paranoá',
    'Modelo Feminino',
    'Contato',
    'Sim',
    'https://randomuser.me/api/portraits/women/9.jpg',
    'SIM',
    null,
    155.00,
    NULL,
    NOW() - INTERVAL '2 hours'
  ),
  
  -- Perfil 10: João Gabriel
  (
    'João Gabriel',
    '(81) 98678-9012',
    'joao.gabriel@email.com',
    '29',
    'Recife Style',
    'Beatriz Nunes',
    'João Pedro',
    'Boa Viagem, Recife',
    -8.1137,
    -34.8988,
    'Praia de Boa Viagem',
    'Modelo Masculino',
    'Contato',
    'Sim',
    'https://randomuser.me/api/portraits/men/10.jpg',
    'SIM',
    'Sim',
    165.00,
    NULL,
    NOW() - INTERVAL '1 hour'
  );

-- Comentário indicando que são dados de teste
COMMENT ON TABLE public.fichas IS 'Tabela de fichas/leads. Contém 10 perfis fictícios para teste da funcionalidade Tinder.';
